// AUTO-GENERATED by scripts/update-flavors.mjs — do not edit by hand.
// Source: https://drinkspindrift.com/collections/sparkling-water/products.json?limit=250
// Last updated: 2026-06-22 · 23 flavors.
// To change accent colors or ordering, edit scripts/update-flavors.mjs and re-run it.
const FLAVORS = [
  {id:"lime",name:"Lime",color:"#8CC63F",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/spindrift-sparkling-product-lime.jpg?v=1747678280"},
  {id:"lemon",name:"Lemon",color:"#F4D03F",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/spindrift-sparkling-product-lemon_9c283b31-99b1-4d47-804d-0faeea24b964.jpg?v=1747678226"},
  {id:"grapefruit",name:"Grapefruit",color:"#F2786E",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/spindrift-sparkling-product-grapefruit.jpg?v=1747677563"},
  {id:"raspberry-lime",name:"Raspberry Lime",color:"#D6336C",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/spindrift-sparkling-product-raspberry-lime.jpg?v=1747678636"},
  {id:"cranberry-raspberry",name:"Cranberry Raspberry",color:"#C2185B",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/spindrift-sparkling-product-cranberry-raspberry.jpg?v=1747677359"},
  {id:"cherry",name:"Cherry",color:"#D8232A",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/spindrift-sparkling-product-cherry.jpg?v=1767889765"},
  {id:"blood-orange-tangerine",name:"Blood Orange Tangerine",color:"#E8602C",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/spindrift-sparkling-product-blood-orange.jpg?v=1747677110"},
  {id:"mango-orange",name:"Mango Orange",color:"#F7941D",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/spindrift-sparkling-product-mango-orange.jpg?v=1747678392"},
  {id:"pineapple",name:"Pineapple",color:"#F5C518",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/spindrift-sparkling-product-pineapple.jpg?v=1747678499"},
  {id:"fuji-apple",name:"Fuji Apple",color:"#E94F6B",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/spindrift-sparkling-product-fuji-apple.jpg?v=1747677394"},
  {id:"grapeade",name:"Grapeade",color:"#7E57C2",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/spindrift-sparkling-product-grapeade.jpg?v=1747677466"},
  {id:"yuzu-mandarin",name:"Yuzu Mandarin",color:"#F5A623",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/spindrift-sparkling-product-yuzu-mandarin.jpg?v=1750456035"},
  {id:"lemon-limeade",name:"Lemon Limeade",color:"#C0D94A",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/spindrift-sparkling-product-lemon-limeade.jpg?v=1747678139"},
  {id:"pink-lemonade",name:"Pink Lemonade",color:"#F06292",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/spindrift-sparkling-product-pink-lemonade.jpg?v=1747678582"},
  {id:"strawberry-lemonade",name:"Strawberry Lemonade",color:"#EF5A78",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/spindrift-sparkling-product-strawberry-lemonade.jpg?v=1747678766"},
  {id:"blueberry-lemonade",name:"Blueberry Lemonade",color:"#5C6BC0",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/Spin_BL_Color_1500x1500_114c2c0f-1a03-4be6-b17a-ce858c2a8d35.jpg?v=1777295422"},
  {id:"tropical-lemonade",name:"Tropical Lemonade",color:"#F6C04A",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/spindrift-sparkling-product-tropical-lemonade.jpg?v=1747679070"},
  {id:"half-tea-half-lemon",name:"Half Tea & Half Lemon",color:"#D9A441",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/spindrift-sparkling-product-half-tea-half-lemon.jpg?v=1747677726"},
  {id:"island-punch",name:"Island Punch",color:"#F4623A",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/spindrift-sparkling-product-island-punch.jpg?v=1747677789"},
  {id:"berry-belli-no",name:"Berry Belli-no",color:"#E26A8D",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/Spindrift_Shopify_berry_bellino.jpg?v=1749738349"},
  {id:"cosnopolitan",name:"Cosnopolitan",color:"#E0457B",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/spindrift-sparkling-product-cosnopolitan.jpg?v=1747677291"},
  {id:"nojito",name:"Nojito",color:"#8DC63F",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/spindrift-sparkling-product-nojito.jpg?v=1747678432"},
  {id:"ginger-lime-mule",name:"Ginger Lime Mule",color:"#C9D94A",img:"https://cdn.shopify.com/s/files/1/1962/5173/files/spindrift-can-hero-ginger-lime-mule-2026.png?v=1767710824"},
];
