#!/usr/bin/env node
/*
 * Regenerates flavors.js from Spindrift's live sparkling-water collection.
 *
 * Run locally:   node scripts/update-flavors.mjs
 * In CI:         see .github/workflows/update-flavors.yml (weekly + manual)
 *
 * Known flavors keep their hand-picked accent color (CURATED_COLORS) and
 * appear in a stable order (ORDER). Any brand-new flavor Spindrift adds is
 * picked up automatically with a deterministic generated color, so the app
 * never silently misses a flavor.
 */

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const SOURCE_URL =
  "https://drinkspindrift.com/collections/sparkling-water/products.json?limit=250";

// Hand-picked, fruit-inspired accent colors, keyed by flavor slug.
const CURATED_COLORS = {
  lime: "#8CC63F",
  lemon: "#F4D03F",
  grapefruit: "#F2786E",
  "raspberry-lime": "#D6336C",
  "cranberry-raspberry": "#C2185B",
  cherry: "#D8232A",
  "blood-orange-tangerine": "#E8602C",
  "mango-orange": "#F7941D",
  pineapple: "#F5C518",
  "fuji-apple": "#E94F6B",
  grapeade: "#7E57C2",
  "yuzu-mandarin": "#F5A623",
  "lemon-limeade": "#C0D94A",
  "pink-lemonade": "#F06292",
  "strawberry-lemonade": "#EF5A78",
  "blueberry-lemonade": "#5C6BC0",
  "tropical-lemonade": "#F6C04A",
  "half-tea-half-lemon": "#D9A441",
  "island-punch": "#F4623A",
  "berry-belli-no": "#E26A8D",
  cosnopolitan: "#E0457B",
  nojito: "#8DC63F",
  "ginger-lime-mule": "#C9D94A",
};

// Preferred display order (classics first). Unknown new flavors are appended.
const ORDER = Object.keys(CURATED_COLORS);

function cleanName(title) {
  return title
    .replace(/[™®©]/g, "")
    .replace(/\bsparkling water\b/gi, "")
    .replace(/\s+/g, " ")
    .trim();
}

function slugify(name) {
  return name
    .toLowerCase()
    .replace(/&/g, " ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// Deterministic pleasant color for flavors we haven't curated.
function generatedColor(slug) {
  let h = 0;
  for (let i = 0; i < slug.length; i++) h = (h * 31 + slug.charCodeAt(i)) >>> 0;
  const hue = h % 360;
  return hslToHex(hue, 62, 55);
}

function hslToHex(h, s, l) {
  s /= 100;
  l /= 100;
  const k = (n) => (n + h / 30) % 12;
  const a = s * Math.min(l, 1 - l);
  const f = (n) => l - a * Math.max(-1, Math.min(k(n) - 3, Math.min(9 - k(n), 1)));
  const to = (x) =>
    Math.round(255 * x)
      .toString(16)
      .padStart(2, "0")
      .toUpperCase();
  return `#${to(f(0))}${to(f(8))}${to(f(4))}`;
}

async function main() {
  const res = await fetch(SOURCE_URL, { headers: { "User-Agent": "spindrift-elo-bot" } });
  if (!res.ok) throw new Error(`Fetch failed: ${res.status} ${res.statusText}`);
  const { products } = await res.json();

  const flavors = products.map((p) => {
    const name = cleanName(p.title);
    const slug = slugify(name);
    const img = (p.images && p.images[0] && p.images[0].src) || "";
    return { id: slug, name, color: CURATED_COLORS[slug] || generatedColor(slug), img };
  });

  // Drop anything without an image, dedupe by id, then sort by ORDER.
  const seen = new Set();
  const unique = flavors.filter((f) => f.img && !seen.has(f.id) && seen.add(f.id));
  unique.sort((a, b) => {
    const ia = ORDER.indexOf(a.id);
    const ib = ORDER.indexOf(b.id);
    return (ia === -1 ? 999 : ia) - (ib === -1 ? 999 : ib);
  });

  const fresh = unique.filter((f) => !ORDER.includes(f.id)).map((f) => f.name);
  const stamp = new Date().toISOString().slice(0, 10);

  const body = unique
    .map(
      (f) =>
        `  ${JSON.stringify({ id: f.id, name: f.name, color: f.color, img: f.img })},`
    )
    .join("\n")
    .replace(/"id":/g, "id:")
    .replace(/"name":/g, "name:")
    .replace(/"color":/g, "color:")
    .replace(/"img":/g, "img:");

  const out = `// AUTO-GENERATED by scripts/update-flavors.mjs — do not edit by hand.
// Source: ${SOURCE_URL}
// Last updated: ${stamp} · ${unique.length} flavors.
// To change accent colors or ordering, edit scripts/update-flavors.mjs and re-run it.
const FLAVORS = [
${body}
];
`;

  const here = dirname(fileURLToPath(import.meta.url));
  await writeFile(join(here, "..", "flavors.js"), out);

  console.log(`Wrote flavors.js with ${unique.length} flavors (${stamp}).`);
  if (fresh.length) console.log(`New flavor(s) auto-added: ${fresh.join(", ")}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
